namespace TradingBot.Domain.Model;

/// <summary>
/// Represents a trade signal generated by a strategy.
/// </summary>
public class TradeSignalModel
{
    /// <summary>
    /// Gets or sets the ticker name of the asset (e.g., BTC, ETH).
    /// </summary>
    public string TickerName { get; set; }

    /// <summary>
    /// Gets or sets the quantity of the asset to be traded.
    /// </summary>
    public decimal Quantity { get; set; }

    /// <summary>
    /// Gets or sets the trade action (e.g., Buy, Sell).
    /// </summary>
    public TradeAction Action { get; set; }

    /// <summary>
    /// Gets or sets the strategy that generated this signal.
    /// </summary>
    public string StrategyName { get; set; }

    /// <summary>
    /// Gets or sets the timestamp when the signal was generated.
    /// </summary>
    public DateTimeOffset Timestamp { get; set; }
}

/// <summary>
/// Represents the action of a trade.
/// </summary>
public enum TradeAction
{
    Sell,
    Buy,
}
