//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

module TradingBot.Api.Features.Profile.Model {
	export interface IPortfolio
	{
		Exchange: string;
		Positions: TradingBot.Api.Features.Profile.Model.IPosition[];
		TotalValue: number;
	}
	export interface IPosition
	{
		Exchange: string;
		Name: string;
		Quantity: number;
		CurrentPrice: number;
		TotalValue: number;
		Timestamp: any;
	}
}
